# -*- coding: utf-8 -*-
"""Final code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i0KVdn4QEoUOU11OCtZPFs0lG_batwBt
"""

# ==========================================================
# STEP 0: MASTER SETUP & DRIVE MOUNT
# ==========================================================
# Run this cell every time you open the notebook!

from google.colab import drive
import os

# 1. Mount your Google Drive
print("Mounting Google Drive...")
drive.mount('/content/drive')

# 2. Define your project path
# This is the single most important variable.
# Change 'My_MTech_Project' if you used a different folder name.
DRIVE_PROJECT_PATH = '/content/drive/My Drive/my_mtech_project'

# 3. Define all your file paths
# We will use these variables throughout the script
DATASET_PATH = f'{DRIVE_PROJECT_PATH}/senti.800k.csv'
BEST_MODEL_PATH = f'{DRIVE_PROJECT_PATH}/best_sentiment_model'
FINAL_MODEL_PATH = f'{DRIVE_PROJECT_PATH}/final_sentiment_model'
LR_MODEL_PATH = f'{DRIVE_PROJECT_PATH}/lr_model.pkl'
TFIDF_PATH = f'{DRIVE_PROJECT_PATH}/tfidf_vectorizer.pkl'
RNN_MODEL_PATH = f'{DRIVE_PROJECT_PATH}/lstm_model.pt'
RNN_VOCAB_PATH = f'{DRIVE_PROJECT_PATH}/rnn_vocab.pkl'
RESULTS_IMG_PATH = f'{DRIVE_PROJECT_PATH}/800k_training_results.png'

# 4. Check if paths are valid
if not os.path.exists(DATASET_PATH):
    print("="*50)
    print(f"ERROR: Dataset not found at {DATASET_PATH}")
    print("Please make sure you uploaded 'senti.800k.csv' to your 'My_MTech_Project' folder in Google Drive.")
    print("="*50)
else:
    print(f"Successfully mounted drive and found dataset at: {DATASET_PATH}")
    print(f"All model outputs will be saved to: {DRIVE_PROJECT_PATH}")

# STEP 1 -> Install Packages and System Check
print("PART A: Starting DistilBERT 800k Training...")
!pip install transformers torch scikit-learn accelerate

import torch
import pandas as pd
import numpy as np
from transformers import DistilBertTokenizer, DistilBertForSequenceClassification
import matplotlib.pyplot as plt
import warnings
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from torch.optim import AdamW
from transformers import get_linear_schedule_with_warmup
from tqdm import tqdm

warnings.filterwarnings('ignore')

print("System Check:")
print(f"PyTorch version: {torch.__version__}")

# Check GPU availability
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

# STEP 2 -> Load 800k Dataset
# NOTE: Ensure 'senti.800k.csv' is uploaded to your Colab environment
print("\nLoading 800k dataset...")
try:
    df = pd.read_csv(DATASET_PATH)
    print(f"Dataset loaded: {len(df):,} samples")
    print(f"Columns: {df.columns.tolist()}")
    print(f"Balance check:\n{df['sentiment'].value_counts()}")
except FileNotFoundError:
    print("Error: 'senti.800k.csv' not found.")
    print("Please upload your dataset to Colab before proceeding.")
    # Create a dummy df to prevent crashes, but training will fail
    df = pd.DataFrame({
        'text': ['dummy data', 'more dummy data'],
        'sentiment': [1, 0]
    })

if len(df) > 100: # Check if we have the real dataset
    # STEP 3 -> Initialize Tokenizer and Test
    print("\nInitializing tokenizer...")
    tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

    # Test tokenizer with sample text
    test_text = df['text'].iloc[0]
    print(f"Sample text: {test_text}")

    encoded = tokenizer(test_text, truncation=True, padding='max_length',
                       max_length=128, return_tensors='pt')
    print(f"Tokenized shape: {encoded['input_ids'].shape}")
    print("Tokenizer working correctly")

    # STEP 4 -> Create Dataset Class
    class SentimentDataset(Dataset):
        def __init__(self, texts, labels, tokenizer, max_length=128):
            self.texts = texts
            self.labels = labels
            self.tokenizer = tokenizer
            self.max_length = max_length

        def __len__(self):
            return len(self.texts)

        def __getitem__(self, idx):
            text = str(self.texts[idx])
            label = self.labels[idx]

            encoding = self.tokenizer(
                text, truncation=True, padding='max_length',
                max_length=self.max_length, return_tensors='pt'
            )

            return {
                'input_ids': encoding['input_ids'].flatten(),
                'attention_mask': encoding['attention_mask'].flatten(),
                'labels': torch.tensor(label, dtype=torch.long)
            }

    # STEP 5 -> Test Model Loading and Quick Training (on 5k sample)
    print("\nCreating and testing on small 5k test dataset...")
    df_test = df.sample(n=5000, random_state=42)

    test_train_texts, test_val_texts, test_train_labels, test_val_labels = train_test_split(
        df_test['text'].tolist(), df_test['sentiment'].tolist(),
        test_size=0.2, random_state=42, stratify=df_test['sentiment']
    )

    test_train_dataset = SentimentDataset(test_train_texts, test_train_labels, tokenizer)
    test_val_dataset = SentimentDataset(test_val_texts, test_val_labels, tokenizer)

    test_train_loader = DataLoader(test_train_dataset, batch_size=16, shuffle=True)
    test_val_loader = DataLoader(test_val_dataset, batch_size=16)

    model_test = DistilBertForSequenceClassification.from_pretrained(
        'distilbert-base-uncased', num_labels=2
    )
    model_test.to(device)

    def quick_train_test(model, train_loader, val_loader, device):
        optimizer = AdamW(model.parameters(), lr=2e-5)
        model.train()
        print("Running quick training test with 5k samples...")
        for batch in tqdm(train_loader, desc="Test Training"):
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['labels'].to(device)
            optimizer.zero_grad()
            outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
            loss = outputs.loss
            loss.backward()
            optimizer.step()

        model.eval()
        correct, total = 0, 0
        with torch.no_grad():
            for batch in val_loader:
                input_ids, attention_mask, labels = batch['input_ids'].to(device), batch['attention_mask'].to(device), batch['labels'].to(device)
                outputs = model(input_ids=input_ids, attention_mask=attention_mask)
                _, predicted = torch.max(outputs.logits.data, 1)
                total += labels.size(0)
                correct += (predicted == labels).sum().item()
        accuracy = 100 * correct / total
        print(f"Quick test accuracy: {accuracy:.2f}%")
        return accuracy

    test_accuracy = quick_train_test(model_test, test_train_loader, test_val_loader, device)
    if test_accuracy > 60:
        print("Quick test passed. Ready for full training.")
    else:
        print("Quick test failed. Check your setup.")
    del model_test # Clear memory

    # STEP 6 -> Prepare Full 800k Dataset
    print("\nPreparing full 800k dataset for training...")
    train_texts, val_texts, train_labels, val_labels = train_test_split(
        df['text'].tolist(),
        df['sentiment'].tolist(),
        test_size=0.1,  # Use 10% for validation
        random_state=42,
        stratify=df['sentiment']
    )
    print(f"Full training samples: {len(train_texts):,}")
    print(f"Full validation samples: {len(val_texts):,}")

    train_dataset = SentimentDataset(train_texts, train_labels, tokenizer)
    val_dataset = SentimentDataset(val_texts, val_labels, tokenizer)

    batch_size = 8
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size)
    print(f"Batch size: {batch_size}")
    print(f"Training batches: {len(train_loader):,}")
    print(f"Validation batches: {len(val_loader):,}")

    # STEP 7 -> Setup Training Configuration
    model = DistilBertForSequenceClassification.from_pretrained(
        'distilbert-base-uncased', num_labels=2
    )
    model.to(device)

    epochs = 3
    learning_rate = 2e-5
    optimizer = AdamW(model.parameters(), lr=learning_rate)
    total_steps = len(train_loader) * epochs
    scheduler = get_linear_schedule_with_warmup(
        optimizer, num_warmup_steps=0, num_training_steps=total_steps
    )
    print(f"Training configuration set for {epochs} epochs.")

    # STEP 8 -> Training Functions with Checkpoints
    def train_epoch(model, data_loader, optimizer, device, scheduler, epoch_num, batch_size):
        model.train()
        total_loss = 0
        correct_predictions = 0
        progress_bar = tqdm(data_loader, desc=f"Training Epoch {epoch_num}")

        for batch_idx, batch in enumerate(progress_bar):
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['labels'].to(device)

            optimizer.zero_grad()
            outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
            loss = outputs.loss
            logits = outputs.logits

            _, preds = torch.max(logits, dim=1)
            correct_predictions += torch.sum(preds == labels)
            total_loss += loss.item()

            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()
            scheduler.step()

            current_acc = correct_predictions.double() / ((batch_idx + 1) * batch_size)
            progress_bar.set_postfix({'loss': f'{loss.item():.4f}', 'acc': f'{current_acc:.4f}'})

            if (batch_idx + 1) % 10000 == 0:
                checkpoint_path = f'{DRIVE_PROJECT_PATH}/checkpoint_epoch_{epoch_num}_step_{batch_idx + 1}.pt'
                torch.save({
                    'epoch': epoch_num, 'step': batch_idx + 1,
                    'model_state_dict': model.state_dict(),
                    'optimizer_state_dict': optimizer.state_dict(),
                    'loss': loss.item(), 'accuracy': current_acc.item()
                }, checkpoint_path)
                print(f"\nCheckpoint saved: {checkpoint_path}")

        return correct_predictions.double() / len(data_loader.dataset), total_loss / len(data_loader)

    def eval_model(model, data_loader, device):
        model.eval()
        total_loss, correct_predictions = 0, 0
        with torch.no_grad():
            for batch in tqdm(data_loader, desc="Evaluating"):
                input_ids, attention_mask, labels = batch['input_ids'].to(device), batch['attention_mask'].to(device), batch['labels'].to(device)
                outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
                total_loss += outputs.loss.item()
                _, preds = torch.max(outputs.logits, dim=1)
                correct_predictions += torch.sum(preds == labels)
        return correct_predictions.double() / len(data_loader.dataset), total_loss / len(data_loader)

    # STEP 9 -> Start Full Training
    print("\n" + "="*60)
    print("Starting Full 800k Training (This will take 12-15 hours)")
    print("="*60)

    history = {'train_acc': [], 'train_loss': [], 'val_acc': [], 'val_loss': []}
    best_val_acc = 0

    for epoch in range(epochs):
        print(f'\nEpoch {epoch + 1}/{epochs}')
        print('='*50)

        train_acc, train_loss = train_epoch(model, train_loader, optimizer, device, scheduler, epoch + 1, batch_size)
        print(f'Training - Loss: {train_loss:.4f}, Accuracy: {train_acc:.4f}')

        val_acc, val_loss = eval_model(model, val_loader, device)
        print(f'Validation - Loss: {val_loss:.4f}, Accuracy: {val_acc:.4f}')

        history['train_acc'].append(train_acc.cpu().item())
        history['train_loss'].append(train_loss)
        history['val_acc'].append(val_acc.cpu().item())
        history['val_loss'].append(val_loss)

        if val_acc > best_val_acc:
            best_val_acc = val_acc
            model.save_pretrained(BEST_MODEL_PATH)
            tokenizer.save_pretrained(BEST_MODEL_PATH)
            print(f"New best validation accuracy: {best_val_acc:.4f}. Model saved.")

        torch.save({
            'epoch': epoch + 1, 'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'val_acc': val_acc.item(), 'history': history
        }, f'epoch_{epoch + 1}_final.pt')
        print(f'Epoch {epoch + 1} checkpoint saved.')

    # STEP 10 -> Save Final Model and Create Results
    model.save_pretrained(FINAL_MODEL_PATH)
    tokenizer.save_pretrained(FINAL_MODEL_PATH)

    print("\n" + "="*60)
    print("PART A Training Completed")
    print(f"Best validation accuracy: {best_val_acc:.4f}")
    print("Models saved to BEST_MODEL_PATH and FINAL_MODEL_PATH")

    # Create training visualization
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))
    epochs_range = range(1, epochs + 1)

    ax1.plot(epochs_range, history['train_acc'], 'b-', label='Training', marker='o')
    ax1.plot(epochs_range, history['val_acc'], 'r-', label='Validation', marker='s')
    ax1.set_title('Model Accuracy')
    ax1.set_xlabel('Epochs')
    ax1.set_ylabel('Accuracy')
    ax1.legend()
    ax1.grid(True, alpha=0.3)

    ax2.plot(epochs_range, history['train_loss'], 'b-', label='Training', marker='o')
    ax2.plot(epochs_range, history['val_loss'], 'r-', label='Validation', marker='s')
    ax2.set_title('Model Loss')
    ax2.set_xlabel('Epochs')
    ax2.set_ylabel('Loss')
    ax2.legend()
    ax2.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(RESULTS_IMG_PATH)
    plt.show()

    print("\nTraining visualization saved as RESULTS_IMG_PATH")
    print("PART A is complete. You can now run PART B.")

else:
    print("\nDummy data detected. Skipping PART A.")
    print("Please upload 'senti.800k.csv' and re-run PART A to train the model.")

print("PART B: Building the Hybrid System")
print("\nSTEP 11: Installing required libraries...")
!pip install emoji --quiet
!pip install transformers --quiet # Ensure transformers is installed in this session

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import pandas as pd
import numpy as np
import re
import emoji
import joblib
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import DistilBertTokenizer, DistilBertForSequenceClassification
from torch.nn.utils.rnn import pad_sequence
import warnings
warnings.filterwarnings('ignore')

# Setup device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

print("\nSTEP 12: Defining Advanced Preprocessing Function...")

# This slang dictionary can be expanded significantly
SLANG_DICT = {
    "lol": "laughing out loud",
    "brb": "be right back",
    "imo": "in my opinion",
    "imho": "in my humble opinion",
    "thx": "thanks",
    "plz": "please",
    "u": "you",
    "r": "are",
    "w/": "with",
    "b/c": "because",
    "omg": "oh my god",
    "idk": "i don't know",
    "idc": "i don't care",
    "np": "no problem",
    "ttyl": "talk to you later"
}

def preprocess_text(text):
    """
    Cleans and preprocesses text for ML/RNN models.
    - Converts emojis to text
    - Replaces common slang
    - Removes URLs, user mentions, and hashtags
    - Removes special characters and numbers
    - Converts to lowercase
    """
    if not isinstance(text, str):
        text = str(text)

    # 1. Convert emojis to text descriptions
    text = emoji.demojize(text, delimiters=(" ", " ")) # "I ❤️" -> "I :red_heart: "
    text = text.replace("_", " ") # "red_heart" -> "red heart"

    # 2. Remove URLs
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)

    # 3. Remove user @mentions
    text = re.sub(r'@\w+', '', text)

    # 4. Remove #hashtags (keep the text)
    text = re.sub(r'#(\w+)', r'\1', text)

    # 5. Convert to lowercase
    text = text.lower()

    # 6. Replace slang
    # This is a simple implementation; a more robust one would use word boundaries
    words = text.split()
    reformed = [SLANG_DICT[word] if word in SLANG_DICT else word for word in words]
    text = " ".join(reformed)

    # 7. Remove non-alphabetic characters (but keep spaces)
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    # 8. Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    return text

# Test the function
test_case = "OMG I ❤️ this product, it's amazing!!! Thx @company #awesome http://test.com"
print(f"Original: {test_case}")
print(f"Processed: {preprocess_text(test_case)}")

print("\nSTEP 13: Training Model 2 (Logistic Regression)...")
print("Loading 800k dataset...")
try:
    df = pd.read_csv(DATASET_PATH)

    # Create a smaller, stratified subset for fast training
    print("Creating 50,000 sample subset for LR/RNN training...")
    df_subset, _ = train_test_split(df, train_size=50000, random_state=42, stratify=df['sentiment'])

    # Preprocess the text for the LR model
    print("Preprocessing texts for LR model...")
    df_subset['processed_text'] = df_subset['text'].apply(preprocess_text)

    # Split the subset
    X_train_lr, X_val_lr, y_train_lr, y_val_lr = train_test_split(
        df_subset['processed_text'],
        df_subset['sentiment'],
        test_size=0.2,
        random_state=42
    )

    # 1. TF-IDF Vectorization
    print("Fitting TF-IDF Vectorizer...")
    tfidf_vectorizer = TfidfVectorizer(max_features=10000, ngram_range=(1, 2))
    X_train_tfidf = tfidf_vectorizer.fit_transform(X_train_lr)
    X_val_tfidf = tfidf_vectorizer.transform(X_val_lr)

    # 2. Train Logistic Regression
    print("Training Logistic Regression model...")
    lr_model = LogisticRegression(solver='liblinear', random_state=42, C=1.0)
    lr_model.fit(X_train_tfidf, y_train_lr)

    # 3. Evaluate and Save
    y_pred_lr = lr_model.predict(X_val_tfidf)
    lr_acc = accuracy_score(y_val_lr, y_pred_lr)
    print(f"Logistic Regression Validation Accuracy: {lr_acc*100:.2f}%")

    joblib.dump(lr_model, LR_MODEL_PATH)
    joblib.dump(tfidf_vectorizer, TFIDF_PATH)
    print("Logistic Regression model and vectorizer saved.")

except FileNotFoundError:
    print("Error: 'senti.800k.csv' not found. Cannot train LR/RNN models.")
    # Create dummy files to prevent crashes, but demo will be meaningless
    joblib.dump(LogisticRegression(), LR_MODEL_PATH)
    joblib.dump(TfidfVectorizer(), TFIDF_PATH)

print("\nSTEP 14: Training Model 3 (RNN/LSTM)...")

# We need to build a custom vocabulary for the RNN's Embedding layer
class RnnVocab:
    def __init__(self, max_features=10000):
        self.word2idx = {'<PAD>': 0, '<UNK>': 1}
        self.idx2word = {0: '<PAD>', 1: '<UNK>'}
        self.max_features = max_features
        self.vectorizer = CountVectorizer(max_features=max_features, stop_words='english')

    def fit(self, texts):
        self.vectorizer.fit(texts)
        for i, word in enumerate(self.vectorizer.get_feature_names_out(), 2):
            self.word2idx[word] = i
            self.idx2word[i] = word

    def transform(self, text):
        words = text.split()
        return [self.word2idx.get(word, 1) for word in words] # 1 is <UNK>

    def __len__(self):
        return len(self.word2idx)

# Create and fit the vocabulary on the same training data
# We use the *same* preprocessed text from the LR step
try:
    rnn_vocab = RnnVocab(max_features=10000)
    rnn_vocab.fit(X_train_lr) # X_train_lr is the processed text
    print(f"RNN Vocabulary created with {len(rnn_vocab)} tokens.")

    # Save the vocabulary
    joblib.dump(rnn_vocab, RNN_VOCAB_PATH)
    print("RNN Vocabulary saved.")

    # Create the RNN Dataset
    class RnnSentimentDataset(Dataset):
        def __init__(self, texts, labels, vocab, max_length=128):
            self.texts = texts
            self.labels = labels
            self.vocab = vocab
            self.max_length = max_length

        def __len__(self):
            return len(self.texts)

        def __getitem__(self, idx):
            text = self.texts.iloc[idx]
            label = self.labels.iloc[idx]

            # Transform text to indices
            token_ids = self.vocab.transform(text)

            # Truncate or pad
            if len(token_ids) > self.max_length:
                token_ids = token_ids[:self.max_length]

            return torch.tensor(token_ids, dtype=torch.long), torch.tensor(label, dtype=torch.long)

    # Padding collate function for DataLoader
    def collate_fn_pad(batch):
        texts, labels = zip(*batch)
        # Pad sequences to the max length in this batch
        texts_padded = pad_sequence(texts, batch_first=True, padding_value=0) # 0 is <PAD>
        labels = torch.stack(labels)
        return texts_padded, labels

    # Create RNN DataLoaders
    rnn_train_dataset = RnnSentimentDataset(X_train_lr, y_train_lr, rnn_vocab)
    rnn_val_dataset = RnnSentimentDataset(X_val_lr, y_val_lr, rnn_vocab)

    rnn_train_loader = DataLoader(rnn_train_dataset, batch_size=32, shuffle=True, collate_fn=collate_fn_pad)
    rnn_val_loader = DataLoader(rnn_val_dataset, batch_size=32, collate_fn=collate_fn_pad)

    # Define the LSTM Model
    class LSTM_Model(nn.Module):
        def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim, n_layers, dropout):
            super().__init__()
            self.embedding = nn.Embedding(vocab_size, embedding_dim, padding_idx=0)
            self.lstm = nn.LSTM(embedding_dim, hidden_dim, num_layers=n_layers,
                                bidirectional=True, batch_first=True, dropout=dropout)
            self.fc = nn.Linear(hidden_dim * 2, output_dim) # *2 for bidirectional
            self.dropout = nn.Dropout(dropout)

        def forward(self, text):
            # text shape: [batch_size, seq_len]
            embedded = self.dropout(self.embedding(text))
            # embedded shape: [batch_size, seq_len, embedding_dim]

            outputs, (hidden, cell) = self.lstm(embedded)
            # outputs shape: [batch_size, seq_len, hidden_dim * 2]

            # Concat the final forward and backward hidden states
            hidden = self.dropout(torch.cat((hidden[-2,:,:], hidden[-1,:,:]), dim=1))
            # hidden shape: [batch_size, hidden_dim * 2]

            return self.fc(hidden)

    # Instantiate the model
    VOCAB_SIZE = len(rnn_vocab)
    EMBEDDING_DIM = 100
    HIDDEN_DIM = 128
    OUTPUT_DIM = 2 # Positive / Negative
    N_LAYERS = 2
    DROPOUT = 0.5

    rnn_model = LSTM_Model(VOCAB_SIZE, EMBEDDING_DIM, HIDDEN_DIM, OUTPUT_DIM, N_LAYERS, DROPOUT).to(device)

    optimizer = optim.Adam(rnn_model.parameters(), lr=1e-3)
    criterion = nn.CrossEntropyLoss().to(device)

    # Training loop for RNN
    print("Training RNN (LSTM) model...")
    rnn_epochs = 5 # This will be fast
    for epoch in range(rnn_epochs):
        rnn_model.train()
        epoch_loss = 0
        for texts_batch, labels_batch in tqdm(rnn_train_loader, desc=f"Epoch {epoch+1}/{rnn_epochs} Training"):
            texts_batch, labels_batch = texts_batch.to(device), labels_batch.to(device)

            optimizer.zero_grad()
            predictions = rnn_model(texts_batch)
            loss = criterion(predictions, labels_batch)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()

        # Validation
        rnn_model.eval()
        correct, total = 0, 0
        with torch.no_grad():
            for texts_batch, labels_batch in rnn_val_loader:
                texts_batch, labels_batch = texts_batch.to(device), labels_batch.to(device)
                predictions = rnn_model(texts_batch)
                _, predicted_labels = torch.max(predictions.data, 1)
                total += labels_batch.size(0)
                correct += (predicted_labels == labels_batch).sum().item()

        rnn_acc = 100 * correct / total
        print(f'Epoch {epoch+1} | Train Loss: {epoch_loss/len(rnn_train_loader):.3f} | Val Acc: {rnn_acc:.2f}%')

    # Save the trained RNN model
    torch.save(rnn_model.state_dict(), RNN_MODEL_PATH)
    print("RNN (LSTM) model saved.")

except FileNotFoundError:
    print("Skipping RNN training as dataset was not found.")
    # Create dummy files
    torch.save(LSTM_Model(100,10,10,2,1,0.5).state_dict(), RNN_MODEL_PATH)
    joblib.dump(RnnVocab(), RNN_VOCAB_PATH)
except Exception as e:
    print(f"An error occurred during RNN training: {e}")
    print("Skipping RNN training.")

# ==========================================================
# ENVIRONMENT FIX (Run this cell before Step 15)
# ==========================================================
print("Force-upgrading 'transformers' and 'huggingface_hub'...")
!pip install --upgrade transformers huggingface_hub
print("Libraries are now up-to-date.")

# ==========================================================
# STEP 15: Load All 4 Models for Inference (CORRECTED)
# ==========================================================

print("\nSTEP 15: Loading All 4 Models for Hybrid Inference...")

try:
    # Model 1: DistilBERT (from Part A)
    print("Loading Model 1: DistilBERT (trained on 800k)...")
    distilbert_model = DistilBertForSequenceClassification.from_pretrained(BEST_MODEL_PATH).to(device)
    distilbert_tokenizer = DistilBertTokenizer.from_pretrained(BEST_MODEL_PATH)
    distilbert_model.eval()
    print("...DistilBERT loaded.")

    # Model 2: Logistic Regression (from Part B)
    print("Loading Model 2: Logistic Regression (trained on 50k)...")
    lr_model = joblib.load(LR_MODEL_PATH)
    tfidf_vectorizer = joblib.load(TFIDF_PATH)
    print("...Logistic Regression loaded.")

    # Model 3: RNN/LSTM (from Part B)
    print("Loading Model 3: RNN/LSTM (trained on 50k)...")
    # Re-load vocab
    rnn_vocab = joblib.load(RNN_VOCAB_PATH)

    # Re-define parameters (they might not be in memory)
    VOCAB_SIZE = len(rnn_vocab)
    EMBEDDING_DIM = 100
    HIDDEN_DIM = 128
    OUTPUT_DIM = 2
    N_LAYERS = 2
    DROPOUT = 0.5

    rnn_model = LSTM_Model(
        vocab_size=VOCAB_SIZE,
        embedding_dim=EMBEDDING_DIM,
        hidden_dim=HIDDEN_DIM,
        output_dim=OUTPUT_DIM,
        n_layers=N_LAYERS,
        dropout=DROPOUT
    ).to(device)

    # Load trained weights
    rnn_model.load_state_dict(torch.load(RNN_MODEL_PATH, map_location=device))
    rnn_model.eval()
    print("...RNN/LSTM loaded.")

    # Model 4: Sarcasm Detector (Pre-trained from Hugging Face)
    print("Loading Model 4: Sarcasm Detector...")

    # --- THIS IS THE FIXED LINE ---
    # 'cardiffnlp/twitter-roberta-base-irony' is the correct, stable model name
    sarcasm_model_name = "cardiffnlp/twitter-roberta-base-irony"
    # ------------------------------

    sarcasm_tokenizer = AutoTokenizer.from_pretrained(sarcasm_model_name)
    sarcasm_model = AutoModelForSequenceClassification.from_pretrained(sarcasm_model_name).to(device)
    sarcasm_model.eval()
    print("...Sarcasm Detector loaded.")

    print("\nAll 4 models are loaded and ready for inference.")

except Exception as e:
    print(f"\nError loading models: {e}")
    print("One or more models failed to load. This may be because Part A was not run,")
    print("or the 'senti.800k.csv' file was missing.")
    print("The final demonstration will likely fail.")

print("\nSTEP 16: Defining the Final Hybrid Prediction Function...")


WEIGHTS = {
    'transformer': 0.6,
    'lr': 0.2,
    'rnn': 0.2
}

def predict_hybrid_sentiment(text):
    """
    Analyzes a single text string using the full hybrid system.
    """
    results = {}

    # 1. Preprocess text for LR/RNN
    processed_text = preprocess_text(text)

    with torch.no_grad():
        # --- Model 1: Sarcasm Prediction (using raw text) ---
        inputs = sarcasm_tokenizer(text, return_tensors='pt', truncation=True, max_length=128).to(device)
        outputs = sarcasm_model(**inputs)
        probs = torch.nn.functional.softmax(outputs.logits, dim=-1)[0]
        sarc_prob = probs[1].item() # Index 1 is 'sarcasm'
        is_sarcastic = sarc_prob > 0.9
        results['sarcasm'] = {
            'label': "Sarcastic" if is_sarcastic else "Not Sarcastic",
            'confidence': sarc_prob if is_sarcastic else 1.0 - sarc_prob
        }

        # --- Model 2: DistilBERT Prediction (using raw text) ---
        inputs = distilbert_tokenizer(text, return_tensors='pt', truncation=True, max_length=128).to(device)
        outputs = distilbert_model(**inputs)
        probs = torch.nn.functional.softmax(outputs.logits, dim=-1)[0]
        results['transformer'] = {
            'label': "Positive" if probs[1] > probs[0] else "Negative",
            'prob_positive': probs[1].item()
        }

        # --- Model 3: Logistic Regression Prediction (using processed text) ---
        tfidf_features = tfidf_vectorizer.transform([processed_text])
        probs = lr_model.predict_proba(tfidf_features)[0]
        results['lr'] = {
            'label': "Positive" if probs[1] > probs[0] else "Negative",
            'prob_positive': probs[1]
        }

        # --- Model 4: RNN/LSTM Prediction (using processed text) ---
        token_ids = rnn_vocab.transform(processed_text)
        if not token_ids: # Handle empty string after processing
            token_ids = [0] # Use <PAD> token
        tensor = torch.tensor([token_ids], dtype=torch.long).to(device)

        prediction = rnn_model(tensor)
        probs = torch.nn.functional.softmax(prediction, dim=-1)[0]
        results['rnn'] = {
            'label': "Positive" if probs[1] > probs[0] else "Negative",
            'prob_positive': probs[1].item()
        }

    # --- Final Combination: Weighted Voting ---
    final_prob_positive = (
        WEIGHTS['transformer'] * results['transformer']['prob_positive'] +
        WEIGHTS['lr'] * results['lr']['prob_positive'] +
        WEIGHTS['rnn'] * results['rnn']['prob_positive']
    )

    results['weighted_average'] = final_prob_positive

    # --- Sarcasm Adjustment ---
    sarcasm_adjusted_prob = final_prob_positive
    adjustment_applied = False

    # If the model is sarcastic AND the initial sentiment is positive,
    # it's likely a negative comment. We invert the sentiment.
    if is_sarcastic and final_prob_positive > 0.5:
        sarcasm_adjusted_prob = 1.0 - final_prob_positive
        adjustment_applied = True

    final_label = "Positive" if sarcasm_adjusted_prob > 0.5 else "Negative"
    final_confidence = max(sarcasm_adjusted_prob, 1.0 - sarcasm_adjusted_prob)

    results['final_prediction'] = {
        'label': final_label,
        'confidence': final_confidence,
        'sarcasm_adjustment_applied': adjustment_applied
    }

    return results

print("Hybrid prediction function defined and ready.")

# ==========================================================
# QUICK RELOAD SETUP (no retraining needed)
# ==========================================================
from google.colab import drive
import os

# Mount drive if not already mounted
if not os.path.exists('/content/drive/My Drive'):
    print("Mounting Google Drive...")
    drive.mount('/content/drive')
else:
    print("Drive already mounted.")

# Define your project folder and all paths again
DRIVE_PROJECT_PATH = '/content/drive/My Drive/my_mtech_project'

DATASET_PATH = f'{DRIVE_PROJECT_PATH}/senti.800k.csv'
BEST_MODEL_PATH = f'{DRIVE_PROJECT_PATH}/best_sentiment_model'
FINAL_MODEL_PATH = f'{DRIVE_PROJECT_PATH}/final_sentiment_model'
LR_MODEL_PATH = f'{DRIVE_PROJECT_PATH}/lr_model.pkl'
TFIDF_PATH = f'{DRIVE_PROJECT_PATH}/tfidf_vectorizer.pkl'
RNN_MODEL_PATH = f'{DRIVE_PROJECT_PATH}/lstm_model.pt'
RNN_VOCAB_PATH = f'{DRIVE_PROJECT_PATH}/rnn_vocab.pkl'

print("✅ Paths restored — ready for evaluation only.")
print("All files will be read/saved from:", DRIVE_PROJECT_PATH)

# ================= EVALUATION CELL (FULL TEST SET) =================

# 0. Install/check dependencies
try:
    import emoji
except Exception:
    !pip install emoji --quiet
    import emoji

import os, joblib, torch, numpy as np, pandas as pd
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
from transformers import DistilBertTokenizer, DistilBertForSequenceClassification
from torch.nn.utils.rnn import pad_sequence
import torch.nn as nn

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("Device:", DEVICE)

# 1) Ensure these variables exist (should be defined in your STEP 0 quick-setup)
try:
    DRIVE_PROJECT_PATH
    DATASET_PATH
    BEST_MODEL_PATH
    LR_MODEL_PATH
    TFIDF_PATH
    RNN_MODEL_PATH
    RNN_VOCAB_PATH
except NameError as ne:
    raise RuntimeError("Run the quick-reload setup cell first (mount drive and set path variables).") from ne

# 2) Minimal RnnVocab definition (needed so joblib.load can reconstruct the object)
#    This must match attribute names used when you created/saved rnn_vocab.
class RnnVocab:
    def __init__(self, max_features=10000):
        self.word2idx = {'<PAD>': 0, '<UNK>': 1}
        self.idx2word = {0: '<PAD>', 1: '<UNK>'}
        self.max_features = max_features
    def transform(self, text):
        # simple split-based transform; joblib will restore saved mapping inside object
        words = str(text).split()
        return [self.word2idx.get(w, 1) for w in words]
    def __len__(self):
        return len(self.word2idx)

# 3) Optional: define LSTM model class (must match saved checkpoint)
class LSTM_Model(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim, n_layers, dropout):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim, padding_idx=0)
        self.lstm = nn.LSTM(embedding_dim, hidden_dim, num_layers=n_layers,
                            bidirectional=True, batch_first=True, dropout=dropout)
        self.fc = nn.Linear(hidden_dim * 2, output_dim)
        self.dropout = nn.Dropout(dropout)
    def forward(self, text):
        embedded = self.dropout(self.embedding(text))
        outputs, (hidden, cell) = self.lstm(embedded)
        hidden_cat = self.dropout(torch.cat((hidden[-2,:,:], hidden[-1,:,:]), dim=1))
        return self.fc(hidden_cat)

# 4) Load dataset and test split (use full held-out test)
df = pd.read_csv(DATASET_PATH)
assert 'text' in df.columns and 'sentiment' in df.columns, "senti.800k.csv must contain 'text' and 'sentiment' columns."

# Ensure deterministic split like earlier (same random_state)
train_df, test_df = train_test_split(df, test_size=0.1, random_state=42, stratify=df['sentiment'])
X_test_texts = test_df['text'].tolist()
y_test = test_df['sentiment'].tolist()
print("Full test set size:", len(y_test))

# 5) Load models & vectorizers (safe try/except to continue if one missing)
distil_model = None; distil_tokenizer = None
lr_model = None; tfidf_vectorizer = None
rnn_model = None; rnn_vocab = None

# DistilBERT
try:
    distil_tokenizer = DistilBertTokenizer.from_pretrained(BEST_MODEL_PATH)
    distil_model = DistilBertForSequenceClassification.from_pretrained(BEST_MODEL_PATH).to(DEVICE)
    distil_model.eval()
    print("Loaded DistilBERT from", BEST_MODEL_PATH)
except Exception as e:
    print("Could not load DistilBERT:", e)

# LR + TF-IDF
try:
    lr_model = joblib.load(LR_MODEL_PATH)
    tfidf_vectorizer = joblib.load(TFIDF_PATH)
    print("Loaded LR and TF-IDF.")
except Exception as e:
    print("Could not load LR/TFIDF:", e)

# RNN vocab + model
try:
    rnn_vocab = joblib.load(RNN_VOCAB_PATH)
    print("Loaded rnn_vocab from", RNN_VOCAB_PATH, "-> vocab size:", len(rnn_vocab))
    # instantiate model using same hyperparams used in training
    VOCAB_SIZE = len(rnn_vocab)
    rnn_model = LSTM_Model(VOCAB_SIZE, embedding_dim=100, hidden_dim=128, output_dim=2, n_layers=2, dropout=0.5).to(DEVICE)
    rnn_model.load_state_dict(torch.load(RNN_MODEL_PATH, map_location=DEVICE))
    rnn_model.eval()
    print("Loaded RNN model.")
except Exception as e:
    print("Could not load RNN model or vocab:", e)

# 6) Preprocess function (use your original if present, otherwise minimal fallback)
try:
    preprocess_text  # if defined earlier in session
except NameError:
    import re
    SLANG_DICT = {"lol":"laughing out loud","brb":"be right back","thx":"thanks","u":"you","r":"are"}
    def preprocess_text(text):
        s = str(text)
        s = emoji.demojize(s, delimiters=(" ", " "))
        s = s.replace("_"," ")
        s = re.sub(r'http\S+|www\S+|https\S+', '', s)
        s = re.sub(r'@\w+', '', s)
        s = re.sub(r'#(\w+)', r'\1', s)
        s = s.lower()
        words = s.split()
        words = [SLANG_DICT.get(w,w) for w in words]
        s = " ".join(words)
        s = re.sub(r'[^a-zA-Z\s]', '', s)
        s = re.sub(r'\s+', ' ', s).strip()
        return s

# 7) helper functions for predictions
def predict_lr(texts):
    if lr_model is None or tfidf_vectorizer is None:
        raise RuntimeError("LR or TF-IDF missing")
    X = tfidf_vectorizer.transform([preprocess_text(t) for t in texts])
    preds = lr_model.predict(X)
    probs = lr_model.predict_proba(X)[:,1] if hasattr(lr_model,'predict_proba') else None
    return preds, probs

def predict_transformer(texts, batch_size=64):
    if distil_model is None or distil_tokenizer is None:
        raise RuntimeError("DistilBERT missing")
    all_preds=[]; all_probs=[]
    with torch.no_grad():
        for i in range(0, len(texts), batch_size):
            batch = texts[i:i+batch_size]
            enc = distil_tokenizer(batch, padding=True, truncation=True, max_length=128, return_tensors='pt')
            input_ids = enc['input_ids'].to(DEVICE)
            attn = enc['attention_mask'].to(DEVICE)
            out = distil_model(input_ids=input_ids, attention_mask=attn)
            logits = out.logits
            probs = torch.nn.functional.softmax(logits, dim=-1)[:,1].cpu().numpy()
            preds = np.argmax(logits.cpu().numpy(), axis=1)
            all_preds.extend(preds.tolist())
            all_probs.extend(probs.tolist())
    return np.array(all_preds), np.array(all_probs)

def texts_to_rnn_tensor(texts):
    seqs=[]
    for t in texts:
        proc = preprocess_text(t)
        ids = rnn_vocab.transform(proc) if rnn_vocab is not None else []
        if len(ids)==0:
            ids=[0]
        seqs.append(torch.tensor(ids,dtype=torch.long))
    padded = pad_sequence(seqs, batch_first=True, padding_value=0)
    return padded

def predict_rnn(texts, batch_size=128):
    if rnn_model is None or rnn_vocab is None:
        raise RuntimeError("RNN missing")
    all_preds=[]; all_probs=[]
    with torch.no_grad():
        for i in range(0, len(texts), batch_size):
            batch = texts[i:i+batch_size]
            tns = texts_to_rnn_tensor(batch).to(DEVICE)
            logits = rnn_model(tns)
            probs = torch.nn.functional.softmax(logits, dim=-1)[:,1].cpu().numpy()
            preds = np.argmax(logits.cpu().numpy(), axis=1)
            all_preds.extend(preds.tolist())
            all_probs.extend(probs.tolist())
    return np.array(all_preds), np.array(all_probs)

# 8) Ensemble prediction (weights as used earlier)
def predict_ensemble(texts, weights=(0.6,0.2,0.2)):
    wt, wlr, wrnn = weights
    N = len(texts)
    # get probabilities if possible
    probs_tr = probs_lr = probs_rnn = None
    try:
        _, probs_tr = predict_transformer(texts)
    except Exception as e:
        print("Transformer probs unavailable:", e)
    try:
        _, probs_lr = predict_lr(texts)
    except Exception as e:
        print("LR probs unavailable:", e)
    try:
        _, probs_rnn = predict_rnn(texts)
    except Exception as e:
        print("RNN probs unavailable:", e)

    final_probs = np.zeros(N, dtype=float)
    weight_sum = 0.0
    if probs_tr is not None:
        final_probs += wt * probs_tr; weight_sum += wt
    if probs_lr is not None:
        final_probs += wlr * probs_lr; weight_sum += wlr
    if probs_rnn is not None:
        final_probs += wrnn * probs_rnn; weight_sum += wrnn
    if weight_sum == 0:
        raise RuntimeError("No model probabilities available for ensemble.")
    final_probs = final_probs / weight_sum
    final_preds = (final_probs >= 0.5).astype(int)
    return final_preds, final_probs

# 9) Run predictions on the full test set (WARNING: may take several minutes on 80k)
TEST_SAMPLE_LIMIT = None  # None uses full test set; set integer for quick run
if TEST_SAMPLE_LIMIT is None:
    X_eval_texts = X_test_texts
    y_eval = y_test
else:
    X_eval_texts = X_test_texts[:TEST_SAMPLE_LIMIT]
    y_eval = y_test[:TEST_SAMPLE_LIMIT]

print("Evaluating on", len(y_eval), "samples...")

results = {}
# LR
try:
    print("Predicting LR...")
    preds_lr, probs_lr = predict_lr(X_eval_texts)
    results['LR'] = (preds_lr, probs_lr)
    print("LR done.")
except Exception as e:
    print("Skipping LR:", e)

# Transformer
try:
    print("Predicting DistilBERT...")
    preds_tr, probs_tr = predict_transformer(X_eval_texts, batch_size=64)
    results['Transformer'] = (preds_tr, probs_tr)
    print("Transformer done.")
except Exception as e:
    print("Skipping Transformer:", e)

# RNN
try:
    print("Predicting RNN...")
    preds_rnn, probs_rnn = predict_rnn(X_eval_texts, batch_size=128)
    results['RNN'] = (preds_rnn, probs_rnn)
    print("RNN done.")
except Exception as e:
    print("Skipping RNN:", e)

# Ensemble
print("Predicting Ensemble...")
preds_ens, probs_ens = predict_ensemble(X_eval_texts, weights=(0.6,0.2,0.2))
results['Ensemble'] = (preds_ens, probs_ens)
print("Ensemble done.")

# 10) Save and print classification reports & confusion matrices
out_reports = []
for name, (preds, probs) in results.items():
    print(f"\n=== Classification Report: {name} ===")
    print(classification_report(y_eval, preds, digits=4))
    df_cr = pd.DataFrame(classification_report(y_eval, preds, digits=4, output_dict=True)).transpose()
    cr_path = os.path.join(DRIVE_PROJECT_PATH, f"classification_report_{name}.csv")
    df_cr.to_csv(cr_path)
    print("Saved report ->", cr_path)

    # confusion matrix
    cm = confusion_matrix(y_eval, preds)
    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Neg','Pos'], yticklabels=['Neg','Pos'])
    plt.title(f"{name} - Confusion Matrix")
    plt.xlabel('Predicted'); plt.ylabel('Actual')
    cm_path = os.path.join(DRIVE_PROJECT_PATH, f"confusion_matrix_{name}.png")
    plt.tight_layout(); plt.savefig(cm_path, dpi=200, bbox_inches='tight'); plt.close()
    print("Saved confusion matrix ->", cm_path)

# 11) Save accuracy comparison bar chart
accs = {name: 100.0*accuracy_score(y_eval, preds) for name,(preds,_) in results.items()}
print("\n--- Accuracy summary (%) ---")
for k,v in accs.items():
    print(f"{k}: {v:.2f}%")
plt.figure(figsize=(7,4))
plt.bar(list(accs.keys()), list(accs.values()))
for i,v in enumerate(list(accs.values())):
    plt.text(i, v+0.5, f"{v:.2f}%", ha='center')
plt.ylabel("Accuracy (%)"); plt.title("Model Accuracy Comparison")
bar_path = os.path.join(DRIVE_PROJECT_PATH, "model_accuracy_comparison_fulltest.png")
plt.tight_layout(); plt.savefig(bar_path, dpi=200, bbox_inches='tight'); plt.close()
print("Saved bar chart ->", bar_path)

# 12) Save ensemble predictions CSV (sample)
ens_df = pd.DataFrame({'text': X_eval_texts, 'label': y_eval, 'ens_prob_pos': results['Ensemble'][1], 'ens_pred': results['Ensemble'][0]})
ens_df.to_csv(os.path.join(DRIVE_PROJECT_PATH, "ensemble_predictions_fulltest.csv"), index=False)
print("Saved ensemble predictions CSV ->", os.path.join(DRIVE_PROJECT_PATH, "ensemble_predictions_fulltest.csv"))

print("\nAll done. Check classification CSVs and PNGs in:", DRIVE_PROJECT_PATH)
# ===================================================================

# Install the emoji library
!pip install emoji --quiet

print("\nSTEP 17: Running Final Demonstration...")
print("="*70)

# A list of test sentences to show the system's capabilities
test_samples = [
    "I love this movie, it's absolutely amazing!",
    "This product is terrible, a complete waste of money.",
    "Oh great, another meeting. Just what I needed.",
    "I just LOVE being stuck in traffic for 2 hours.",
    "The weather is... okay, I guess. Not bad.",
    "This is the best day of my life! So happy!",
    "The app keeps crashing. Very frustrating lol.",
    "Thanks for the 'wonderful' service. Took 3 weeks to get a reply.",
    "u r the best thx for the help ❤️"
]

for i, text in enumerate(test_samples):
    print(f"\nTEST SAMPLE {i+1}")
    print(f"Input Text: '{text}'")
    print("-" * 50)

    try:
        results = predict_hybrid_sentiment(text)

        # --- Print Breakdown ---
        print("MODEL BREAKDOWN:")
        print(f"  - Sarcasm        : {results['sarcasm']['label']} (Conf: {results['sarcasm']['confidence']:.2f})")
        print(f"  - Transformer    : {results['transformer']['label']} (Prob Positive: {results['transformer']['prob_positive']:.2f})")
        print(f"  - Logistic Reg.  : {results['lr']['label']} (Prob Positive: {results['lr']['prob_positive']:.2f})")
        print(f"  - RNN (LSTM)     : {results['rnn']['label']} (Prob Positive: {results['rnn']['prob_positive']:.2f})")

        # --- Print Final Result ---
        print("\nFINAL PREDICTION:")
        print(f"  > Weighted Sentiment (Before Sarcasm): {results['weighted_average']:.2f}")

        if results['final_prediction']['sarcasm_adjustment_applied']:
            print(f"  > SARCASM DETECTED! Adjusting sentiment.")

        print(f"\n  >> FINAL SENTIMENT: {results['final_prediction']['label']}")
        print(f"  >> CONFIDENCE: {results['final_prediction']['confidence']:.3f}")

    except Exception as e:
        print(f"An error occurred while processing this text: {e}")
        print("This likely means one of the models failed to load.")

    print("="*70)

print("\nHybrid System Demonstration Complete.")

# ==========================================================
# STEP 18: Final Interactive Demonstration (User Input)
# ==========================================================

print("\n" + "="*70)
print("     HYBRID SENTIMENT ANALYSIS - INTERACTIVE MODE")
print("="*70)
print("All 4 models are loaded and ready.")
print("Enter a sentence to analyze. Type 'quit' or 'exit' to stop.")

while True:
    print("-" * 70)
    # 1. Get user input
    text = input("\nEnter text: ").strip()

    # 2. Check for exit command
    if text.lower() in ['quit', 'exit', 'q']:
        print("\nGoodbye! Interactive session ended.")
        break

    # 3. Check for empty input
    if not text:
        print("Please enter a sentence.")
        continue

    # 4. Run the full prediction (same logic as Step 17)
    try:
        results = predict_hybrid_sentiment(text)

        # --- Print Breakdown ---
        print("\nMODEL BREAKDOWN:")
        print(f"  - Sarcasm        : {results['sarcasm']['label']} (Conf: {results['sarcasm']['confidence']:.2f})")
        print(f"  - Transformer    : {results['transformer']['label']} (Prob Positive: {results['transformer']['prob_positive']:.2f})")
        print(f"  - Logistic Reg.  : {results['lr']['label']} (Prob Positive: {results['lr']['prob_positive']:.2f})")
        print(f"  - RNN (LSTM)     : {results['rnn']['label']} (Prob Positive: {results['rnn']['prob_positive']:.2f})")

        # --- Print Final Result ---
        print("\nFINAL PREDICTION:")
        print(f"  > Weighted Sentiment (Before Sarcasm): {results['weighted_average']:.2f}")

        if results['final_prediction']['sarcasm_adjustment_applied']:
            print(f"  > SARCASM DETECTED! Adjusting sentiment.")

        print(f"\n  >> FINAL SENTIMENT: {results['final_prediction']['label']}")
        print(f"  >> CONFIDENCE: {results['final_prediction']['confidence']:.3f}")

    except Exception as e:
        print(f"\nAn error occurred while processing this text: {e}")
        print("This likely means one of the models failed to load.")

print("="*70)